CREATE TABLE [Graph].[Teacher] (
    [ID]   INT          NOT NULL,
    [Name] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    INDEX [GRAPH_UNIQUE_INDEX_36F4D1676B0E4FDAAE3F85570BEFB584] UNIQUE NONCLUSTERED ($node_id)
) AS NODE;


GO

